-- Auth service DB schema (extracted from resume_db_schema_2026-02-05.sql)

--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id bigint NOT NULL,
    uid character varying(64) NOT NULL,
    password_hash character varying(255) NOT NULL,
    first_name character varying(64) NOT NULL,
    last_name character varying(64) NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    CONSTRAINT chk_auth_user_uid_format CHECK (((uid)::text ~ '^[a-z0-9_-]{3,64}$'::text)),
    CONSTRAINT chk_auth_user_uid_lowercase CHECK (((uid)::text = lower((uid)::text)))
);

--
-- Name: profile_restore; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_restore (
    id bigint NOT NULL,
    token character varying(64) NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    profile_id bigint NOT NULL
);

--
-- Name: profile_restore_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.profile_restore ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_restore_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: remember_me_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.remember_me_token (
    series character varying(64) NOT NULL,
    token character varying(64) NOT NULL,
    last_used timestamp with time zone NOT NULL,
    profile_id bigint NOT NULL,
    username character varying(64) NOT NULL
);

--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);

--
-- Name: auth_user auth_user_uid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_uid_key UNIQUE (uid);

--
-- Name: profile_restore profile_restore_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_restore
    ADD CONSTRAINT profile_restore_pkey PRIMARY KEY (id);

--
-- Name: profile_restore profile_restore_uid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_restore
    ADD CONSTRAINT profile_restore_uid_key UNIQUE (token);

--
-- Name: remember_me_token remember_me_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.remember_me_token
    ADD CONSTRAINT remember_me_token_pkey PRIMARY KEY (series);

--
-- Name: profile_restore uk_profile_restore_profile; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_restore
    ADD CONSTRAINT uk_profile_restore_profile UNIQUE (profile_id);

--
-- Name: idx_remember_me_profile; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_remember_me_profile ON public.remember_me_token USING btree (profile_id);

--
-- Name: idx_remember_me_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_remember_me_username ON public.remember_me_token USING btree (username);
